# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cache-Funcky-Storage-Memcached
version:      0.01
version_from: lib/Cache/Funcky/Storage/Memcached.pm
installdirs:  site
requires:
    Cache::Funcky:                 0
    Cache::Funcky::Storage:        0
    Cache::Memcached:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
